export default [
  {
    id: 1,
    alt: 'Panadol Antigripal NF Tableta',
    title: 'Panadol Antigripal NF Tableta',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/025891X.jpg',
    price: 2.12,
  },
  {
    id: 2,
    alt: 'Vitapyrena Forte Antigripal Sabor Miel y Limón - Caja 50 UN',
    title: 'Vitapyrena Forte Antigripal Sabor Miel y Limón - Caja 50 UN',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/327091X.jpg',
    price: 10,
  },
  {
    id: 3,
    alt: 'Vick Vaporub Ungüento tópico',
    title: 'Vick Vaporub Ungüento tópico',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/324071X.jpg',
    price: 20,
  },
  {
    id: 4,
    alt: 'Abrilar EA 575 Jarabe',
    title: 'Abrilar EA 575 Jarabe',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/932007X.jpg',
    price: 30,
  },
  {
    id: 5,
    alt: 'Panadol Forte Tableta',
    title: 'Panadol Forte Tableta',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/029509X.jpg',
    price: 50,
  },
  {
    id: 6,
    alt: 'Vick Vaporub Ungüento tópico',
    title: 'Vick Vaporub Ungüento tópico',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/324070X.jpg',
    price: 20,
  },
  {
    id: 7,
    alt: 'Vick 44 Jarabe',
    title: 'Vick 44 Jarabe',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/264050X.jpg',
    price: 12,
  },
  {
    id: 8,
    alt: 'Multi-bioticos Pastilla dura con sabor a Mentol y Eucaliptol',
    title: 'Multi-bioticos Pastilla dura con sabor a Mentol y Eucaliptol',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/261223X.jpg',
    price: 13,
  },
  {
    id: 9,
    alt: 'Panadol 100mg/ml Solución oral gotas',
    title: 'Panadol 100mg/ml Solución oral gotas',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/108220X.jpg',
    price: 15,
  },
  {
    id: 10,
    alt: 'Multi-bioticos Pastilla dura con sabor a Naranja',
    title: 'Multi-bioticos Pastilla dura con sabor a Naranja',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/341039X.jpg',
    price: 4.5,
  },
  {
    id: 11,
    alt: 'Multi-bioticos Caramelos duros con sabor a Menta y Miel sin Azúcar',
    title: 'Multi-bioticos Caramelos duros con sabor a Menta y Miel sin Azúcar',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/034578X.jpg',
    price: 2.6,
  },
  {
    id: 12,
    alt: 'BioGaia Protectis 19mg/ml Suspensión Oral',
    title: 'BioGaia Protectis 19mg/ml Suspensión Oral',
    image: 'https://dcuk1cxrnzjkh.cloudfront.net/imagesproducto/009640X.jpg',
    price: 11.5,
  },
];
